import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Alkholaidi',
      email: 'alkholaidi11@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat1',
      category: 'Women-Coats',
      image: '/images/women-fur-coat1.jpg',
      price: 449,
      brand: 'Tony Grazza',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in white color and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat2',
      category: 'Women-Coats',
      image: '/images/women-fur-coat2.jpg',
      price: 549,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat3',
      category: 'Women-Coats',
      image: '/images/women-fur-coat3.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat4',
      category: 'Women-Coats',
      image: '/images/women-fur-coat4.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description: 'A popular coat',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat5',
      category: 'Women-Coats',
      image: '/images/women-fur-coat5.jpg',
      price: 449,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat6',
      category: 'Women-Coats',
      image: '/images/women-fur-coat6.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat7',
      category: 'Women-Coats',
      image: '/images/women-fur-coat7.jpg',
      price: 449,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat8',
      category: 'Women-Coats',
      image: '/images/women-fur-coat8.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat9',
      category: 'Women-Coats',
      image: '/images/women-fur-coat9.jpg',
      price: 349,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 4,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-jacket',
      slug: 'women-fur-jacket10',
      category: 'Women-Jackets',
      image: '/images/women-fur-jacket10.jpg',
      price: 399,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur jacket is perfect for keeping you warm through the winter. The jacket is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur jacket is available in brown, and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat11',
      category: 'Women-Coats',
      image: '/images/women-fur-coat11.jpg',
      price: 559,
      brand: 'KLAROS',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat12',
      category: 'Women-Coats',
      image: '/images/women-fur-coat12.jpg',
      price: 549,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat13',
      category: 'Women-Coats',
      image: '/images/women-fur-coat13.jpg',
      price: 499,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat14',
      category: 'Women-Coats',
      image: '/images/women-fur-coat14.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat15',
      category: 'Women-Coats',
      image: '/images/women-leather-coat15.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat16',
      category: 'Women-Coats',
      image: '/images/women-leather-coat16.jpg',
      price: 559,
      brand: 'CAN KURK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat17',
      category: 'Women-Coats',
      image: '/images/women-leather-coat17.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-jacket',
      slug: 'women-leather-jacket18',
      category: 'Women-Jackets',
      image: '/images/women-leather-jacket18.jpg',
      price: 499,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat19',
      category: 'Women-Coats',
      image: '/images/women-leather-coat19.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description: 'A popular coat',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat20',
      category: 'Women-Coats',
      image: '/images/women-leather-coat20.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat21',
      category: 'Women-Coats',
      image: '/images/women-leather-coat21.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-coat',
      slug: 'women-leather-coat22',
      category: 'Women-Coats',
      image: '/images/women-leather-coat22.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'women-leather-jacket',
      slug: 'women-leather-jacket23',
      category: 'Women-Jackets',
      image: '/images/women-leather-jacket23.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'With its soft, luxurious leather and flattering fit, this coat will keep you warm and stylish all winter long. The coat is made of sheep leather, which is known for its softness and durability. It features a comfortable wool lining and a stylish hood that will keep you warm and protected from the elements.This coat has a classic fit that will flatter your figure. It features a button closure and two front pockets. The hemline falls just below the hip, making it perfect for wearing over dresses,',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket24',
      category: 'Mens-Jackets',
      image: '/images/mens-leather-jacket24.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket25',
      category: 'Mens-Jackets',
      image: '/images/mens-leather-jacket25.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket26',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket26.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket27',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket27.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket28',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket28.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket29',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket29.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket30',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket30.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket31',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket31.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket32',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket32.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket33',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket33.jpg',
      price: 549,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-bomber-jacket',
      slug: 'mens-bomber-jacket34',
      category: 'mens-Jackets',
      image: '/images/mens-bomber-jacket34.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Bomber Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Bomber Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-biker-jacket',
      slug: 'mens-biker-jacket35',
      category: 'Mens-Coats',
      image: '/images/mens-biker-jacket35.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Biker Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Biker Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket36',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket36.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket37',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket37.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket38',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket38.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket39',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket39.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-biker-jacket',
      slug: 'mens-biker-jacket40',
      category: 'Mens-Coats',
      image: '/images/mens-biker-jacket40.jpg',
      price: 599,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket41',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket41.jpg',
      price: 349,   
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket42',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket42.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket43',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket43.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket44',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket44.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket45',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket45.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket46',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket46.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-jacket',
      slug: 'mens-leather-jacket47',
      category: 'mens-Jackets',
      image: '/images/mens-leather-jacket47.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'mens-leather-coat',
      slug: 'mens-leather-jacket48',
      category: 'mens-Jackets',
      image: '/images/mens-leather-coat48.jpg',
      price: 449,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'This Mens Leather Jacket is a stylish and durable addition to your wardrobe. It is made of high-quality leather with a soft inner lining that keeps you warm and comfortable. The jacket has a stylish design that will make you stand out from the crowd. It also features a number of pockets that provide ample storage for your belongings.This Mens Leather Jacket is perfect for winter weather and can be worn with a variety of outfits. It is also designed to keep you warm in cold weather conditions.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat49',
      category: 'Women-Coats',
      image: '/images/women-fur-coat49.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat50',
      category: 'Women-Coats',
      image: '/images/women-fur-coat50.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat51',
      category: 'Women-Coats',
      image: '/images/women-fur-coat51.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat52',
      category: 'Women-Coats',
      image: '/images/women-fur-coat52.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat53',
      category: 'Women-Coats',
      image: '/images/women-fur-coat53.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat54',
      category: 'Women-Coats',
      image: '/images/women-fur-coat54.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat55',
      category: 'Women-Coats',
      image: '/images/women-fur-coat55.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat56',
      category: 'Women-Coats',
      image: '/images/women-fur-coat56.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat57',
      category: 'Women-Coats',
      image: '/images/women-fur-coat57.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat58',
      category: 'Women-Coats',
      image: '/images/women-fur-coat58.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat59',
      category: 'Women-Coats',
      image: '/images/women-fur-coat59.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat60',
      category: 'Women-Coats',
      image: '/images/women-fur-coat60.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat61',
      category: 'Women-Coats',
      image: '/images/women-fur-coat61.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat62',
      category: 'Women-Coats',
      image: '/images/women-fur-coat62.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat63',
      category: 'Women-Coats',
      image: '/images/women-fur-coat63.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat64',
      category: 'Women-Coats',
      image: '/images/women-fur-coat64.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat65',
      category: 'Women-Coats',
      image: '/images/women-fur-coat65.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat66',
      category: 'Women-Coats',
      image: '/images/women-fur-coat66.jpg',
      price: 399,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat67',
      category: 'Women-Coats',
      image: '/images/women-fur-coat67.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat68',
      category: 'Women-Coats',
      image: '/images/women-fur-coat68.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat69',
      category: 'Women-Coats',
      image: '/images/women-fur-coat69.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat70',
      category: 'Women-Coats',
      image: '/images/women-fur-coat70.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat71',
      category: 'Women-Coats',
      image: '/images/women-fur-coat71.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat72',
      category: 'Women-Coats',
      image: '/images/women-fur-coat72.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat73',
      category: 'Women-Coats',
      image: '/images/women-fur-coat73.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat74',
      category: 'Women-Coats',
      image: '/images/women-fur-coat74.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat75',
      category: 'Women-Coats',
      image: '/images/women-fur-coat75.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat76',
      category: 'Women-Coats',
      image: '/images/women-fur-coat76.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat77',
      category: 'Women-Coats',
      image: '/images/women-fur-coat77.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat78',
      category: 'Women-Coats',
      image: '/images/women-fur-coat78.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat79',
      category: 'Women-Coats',
      image: '/images/women-fur-coat79.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat80',
      category: 'Women-Coats',
      image: '/images/women-fur-coat80.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat81',
      category: 'Women-Coats',
      image: '/images/women-fur-coat81.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat82',
      category: 'Women-Coats',
      image: '/images/women-fur-coat82.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat83',
      category: 'Women-Coats',
      image: '/images/women-fur-coat83.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat84',
      category: 'Women-Coats',
      image: '/images/women-fur-coat84.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat85',
      category: 'Women-Coats',
      image: '/images/women-fur-coat85.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat86',
      category: 'Women-Coats',
      image: '/images/women-fur-coat86.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat87',
      category: 'Women-Coats',
      image: '/images/women-fur-coat87.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat88',
      category: 'Women-Coats',
      image: '/images/women-fur-coat88.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat89',
      category: 'Women-Coats',
      image: '/images/women-fur-coat89.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat90',
      category: 'Women-Coats',
      image: '/images/women-fur-coat90.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat91',
      category: 'Women-Coats',
      image: '/images/women-fur-coat91.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat92',
      category: 'Women-Coats',
      image: '/images/women-fur-coat92.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat93',
      category: 'Women-Coats',
      image: '/images/women-fur-coat93.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat94',
      category: 'Women-Coats',
      image: '/images/women-fur-coat94.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat95',
      category: 'Women-Coats',
      image: '/images/women-fur-coat95.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat96',
      category: 'Women-Coats',
      image: '/images/women-fur-coat96.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat97',
      category: 'Women-Coats',
      image: '/images/women-fur-coat97.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat98',
      category: 'Women-Coats',
      image: '/images/women-fur-coat98.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat99',
      category: 'Women-Coats',
      image: '/images/women-fur-coat99.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat100',
      category: 'Women-Coats',
      image: '/images/women-fur-coat100.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat101',
      category: 'Women-Coats',
      image: '/images/women-fur-coat101.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat102',
      category: 'Women-Coats',
      image: '/images/women-fur-coat102.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat103',
      category: 'Women-Coats',
      image: '/images/women-fur-coat103.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat104',
      category: 'Women-Coats',
      image: '/images/women-fur-coat104.jpg',
      price: 299,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat105',
      category: 'Women-Coats',
      image: '/images/women-fur-coat105.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
    {
      name: 'women-fur-coat',
      slug: 'women-fur-coat106',
      category: 'Women-Coats',
      image: '/images/women-fur-coat106.jpg',
      price: 349,
      brand: 'Turkish',
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
      description:
        'Warm and stylish, this womens fur coat is perfect for keeping you warm through the winter. The coat is made of high-quality faux fur with a comfortable lining that will keep you cozy. It features a hood, long sleeves, and a front closure, as well as two pockets to keep your hands warm.This womens fur coat is available in black, brown, or purple and will add a touch of luxury to any outfit. It makes a great addition to your wardrobe for winter fashion.',
    },
  ],
};

export default data;                                
